### ISSUE TITLE
How to use with standard flow and pkceMethod

### ISSUE THREAD

**Issue by appukuttan-shailesh** [svalabs/cypress-keycloak-commands#4]
I connect to my client in my app using standard flow and pkceMethod set to 'S256'.
```
keycloak
        .init({ flow: 'standard', pkceMethod: 'S256' })
```
How can I specify these when using this package?

**Comment by davidkaufmann** [comment]
Hi @appukuttan-shailesh,

I apologize for getting back so late, but for unknown reasons I didn't get notified by github.
I'm by no means an expert on oauth2 and keycloak and had to ask a colleague what your request is about.
This package currently uses standard flow and doesn't support setting pkce right now.
It is definately possible to add it though - feel free contribute and add a PR!
I will have a look into this myself but I can't promise getting it to work.

**Comment by appukuttan-shailesh** [comment]
Thanks for the update @davidkaufmann
I did find a workaround by authenticating using the GUI approach and then copying over the required token.
I am not very comfortable with oauth2, and so not sure I will be able to take this forward. I shall therefore close this ticket now.
